metadata:
  namespace: default
  type: EtcdBackupS3Configs.omni.sidero.dev
  id: etcd-backup-s3-conf
spec:
  bucket: omni-backups
  region: auto
  endpoint: https://${CF_ACCOUNT_ID}.r2.cloudflarestorage.com
  accesskeyid: ${OMNI_R2_ACCESS_KEY}
  secretaccesskey: ${OMNI_R2_ACCESS_SECRET}
  sessiontoken: ""
