apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://clusterapi.nmoura.pt:8100
    name: omni-homelab
contexts:
  - context:
      cluster: omni-homelab
      namespace: default
      user: omni-homelab-nuno@babybites.pt
    name: omni-homelab
current-context: omni-homelab
users:
- name: omni-homelab-nuno@babybites.pt
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://cluster.nmoura.pt/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:homelab
      command: kubectl
      env: null
      provideClusterInfo: false
