apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cross-seed-config
  namespace: cross-seed
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 5Gi
