apiVersion: v1
kind: Service
metadata:
  name: cross-seed
  namespace: cross-seed
  labels:
    app: cross-seed
spec:
  type: ClusterIP
  ports:
    - port: 2468
      targetPort: 2468
      protocol: TCP
      name: http
  selector:
    app: cross-seed
