services:
  booklore_mariadb:
    container_name: booklore_mariadb
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: booklore
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /volume2/docker/booklore_mariadb/volumes/data:/var/lib/mysql
    ports:
      - "10012:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod_net

networks:
  prod_net:
    external: true
