services:
  nextcloud_pgsql:
    container_name: nextcloud_pgsql
    image: postgres:17
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - /volume2/docker/nextcloud_pgsql/volumes/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: 'cat /initialised.txt && pg_isready -U ${PG_USER}'
      interval: "10s"
      timeout: "5s"
      retries: "5"
    entrypoint: >
      /bin/bash -c '
      docker-entrypoint.sh postgres &
      rm -f /initialised.txt || true &&
      until pg_isready -U ${PG_USER}; do sleep 3; done &&
      psql -U ${PG_USER} -d postgres -c "CREATE DATABASE \"nextcloud\";" || true &&
      echo done > /initialised.txt &&
      wait'
    networks:
      vlan101:
        ipv4_address: "192.168.101.66"

networks:
  vlan101:
    external: true
