
services:
  cloudflared_lis_prod:
    image: cloudflare/cloudflared:2025.6.1
    container_name: cloudflared_lis_prod
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - prod_network

networks:
  prod_network:
    external: true