apiVersion: v1
kind: ConfigMap
metadata:
  name: qbitmanage-config
  namespace: qbitmanage
data:
  config.yml: |
    commands:
      tag_nohardlinks: True
      tag_tracker_error: True
      rem_orphaned: True
      share_limits: True
      tag_update: True

    qbt:
      host: "http://192.168.202.1:10002"
      user: randomuser
      pass: randompass

    settings:
      tracker_error_tag: issue
      nohardlinks_tag: noHL
      share_limits_tag: ~share_limit
      share_limits_min_seeding_time_tag: ""
      share_limits_min_num_seeds_tag: ""
      share_limits_last_active_tag: ""
      cat_filter_completed: True
      share_limits_filter_completed: True
      tag_nohardlinks_filter_completed: True
      cat_update_all: True
      disable_qbt_default_share_limits: True
      tag_stalled_torrents: True

    directory:
      root_dir: "/data/torrents/"
      orphaned_dir: "/data/torrents/orphans"

    cat:
      Uncategorized: "/downloads"
      junk: "/data/torrents/junk"
      lidarr: "/data/torrents/music"
      radarr: "/data/torrents/movies"
      readarr: "/data/torrents/books"
      sonarr: "/data/torrents/series"
      music: "/data/media/music"
      movies: "/data/media/movies"
      books: "/data/media/books"
      series: "/data/media/series"

    cat_change:
      CatA.cross-seed: CatA

    tracker:
      aither:
        tag: Aither
      avistaz:
        tag: AvistaZ
      digitalcore:
        tag: DigitalCore
      fearnopeer:
        tag: FearNoPeer
      milkie:
        tag: Milkie
      myanonamouse:
        tag: MaM
      portugas:
        tag: Portugas
      reelflix:
        tag: Reelflix
      seedpool:
        tag: SeedPool
      torrentleech|tleechreload:
        tag: TorrentLeech
      t-ru:
        tag: RuTracker
      upload:
        tag: UploadCX
      onlyencodes:
        tag: OnlyEncodes
      hd-space:
        tag: HD-Space
      lst:
        tag: LST
      other:
        tag: other

    nohardlinks:
      radarr:
      sonarr:

    share_limits:
      noHL:
        priority: 1
        include_any_tags:
          - noHL
        max_seeding_time: 10d
        cleanup: true
        resume_torrent_after_change: true
        add_group_to_tag: true
      issues:
        priority: 3
        include_any_tags:
          - issue
        max_seeding_time: 10d
        cleanup: true
        resume_torrent_after_change: true
        add_group_to_tag: true
      default:
        priority: 999
        max_ratio: -1
        max_seeding_time: -1
        cleanup: false

    recyclebin:
      enabled: false

    orphaned:
      empty_after_x_days: 30
      exclude_patterns:
        - "**/.DS_Store"
        - "**/Thumbs.db"
        - "**/@eaDir"
        - "/data/torrents/temp/**"
        - "**/*.!qB"
        - "**/*_unpackerred"
      max_orphaned_files_to_delete: -1

    webhooks:
      error: "apprise://apprise.apprise.svc.cluster.local:8000"
      function:
        recheck: "apprise://apprise.apprise.svc.cluster.local:8000"
        cat_update: "apprise://apprise.apprise.svc.cluster.local:8000"
        tag_update: "apprise://apprise.apprise.svc.cluster.local:8000"
        rem_unregistered: "apprise://apprise.apprise.svc.cluster.local:8000"
        tag_tracker_error: "apprise://apprise.apprise.svc.cluster.local:8000"
        rem_orphaned: "apprise://apprise.apprise.svc.cluster.local:8000"
        tag_nohardlinks: "apprise://apprise.apprise.svc.cluster.local:8000"
        share_limits: "apprise://apprise.apprise.svc.cluster.local:8000"
        cleanup_dirs: "apprise://apprise.apprise.svc.cluster.local:8000"
