apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qbitmanage

resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - nfs-pv-pvc.yaml
  - configmap.yaml
  - qbitmanage-secrets.sealedsecret.yaml
