apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qbitmanage-synology
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: qbitmanage
    name: pvc-qbitmanage-synology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbitmanage-synology
  namespace: qbitmanage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-qbitmanage-synology
  storageClassName: ""
