apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitmanage-config
  namespace: qbitmanage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 1Gi
