---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbitmanage-secrets
  namespace: qbitmanage
spec:
  encryptedData:
    APPRISE_NOTIFY_URL: AgCELHcliZEz46C2ALUBlo3c9yHY+NFCbDVlD7vwvP8YUbUxngcNCll7qxgYWDh7fWvtnKZRiz52oFNQ4Fozhp6nJjg7pqualgGpn+yV1CkNkA0xF+FWA4l5UViGlzGJeCt21e3f/B3tC6oLOSxAA0Xh55VdOx5CIZxFCkC2+tE0oCaZis6VjnXyHJ5UvKgjYeRMD24zEFot6CUTICZoRaS9fEudo93D7cTFXvxfJi3DLWhXc1hFLFVqbqe4FJgr+Vtk91CYdvjzdg4cKVHS2B7rI4hyeZRAZDUng9fAgfjSNY2an2KxaLYUsmbnT6RoamJdI5C8Mk6YeM+5U71ms52ICoRy42VYy/Tkh5NZ+I2ibodpcjTtxDHnP0kKz+0FW+xbomJy5We1uAfR3+mRy1qESzgmMb5tEIumkiMcP7dxb/q0ztUZULIM9aoIwDV5cxG8bqQbw4EP8vCK4jEfDT+w9vKhz9A/VeOFAyMOd9qRuTINTslO5VcTXBmLLxW/4szHBNIDIw++RqJHuUxce+T1neCPb+GzyRH+/hP5Iiq/H7OxuQtqQXSD9yCrqjXymCqdvVF1N7RKORRA1IEKXzj426wRMiQNBZLRTlu+xgT8GcZr1LTMk9SG/SiITWZhE/S17egYN1p6eBvWSBaNipoLczBuOppAp39L6sComfAoMdf67a/Zi/BDwToZcGoSRv/IuVOWmg52Zosj+6Pyut6lrPt10iapTG4eMYnp+ob80bjXinfVeF3I9YTQixMHzZQzy4gyLDYTPCD366QkKCUnqA==
  template:
    metadata:
      name: qbitmanage-secrets
      namespace: qbitmanage
    type: Opaque
