---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-secrets
  namespace: apprise
spec:
  encryptedData:
    APPRISE_STATEFUL_MODE: AgBKUGpsOXYdAdZ6KfgZM9Roo3uYfNH8Jkjlv6mbNK7b21mqHmcTtaydIftgvKY0e6kVS1Zd0StEU9KkKI9NEjjp5YbnK9mbV+FVCGn4883142E9VLzgteQPmtwLFtrtob4xQ/vzrQd9bbX8L9+sRxMMxt+etiBSDs4sakLcbgfLd7od9qPVq1sXacWOxq5NtusW0S7FySD9vJPlh73vHXoIQ+fQdpFw4GbtPFx/va+hJcQrYxzrjmRj3393HEMg/U+6tbqDEF9LSCcaMBS29Va8m8tNr9nTytAR6gNR+NKlO4jphSWRyydKA7LnsGbHjmx9XEkScI7oo0EM/eIjIbHtdOXSgT7ad94PJJuHE5u+ypPi/hdVx3ywWPWeCdCDqGv5rMWZqzcTHAAar1mhsaQx9nna4fUBR69KmrBuEc2NNOETQGCyi6kUSofBGn3LEzzFjZp3Fylo4RSFOzewHoQwDcCrWwvLm+WPTyGHTFDKRNQfSjJ5Z4rjRsTWwI91w61/BxF/l2DHRPbNf17HYxYT6+jIZnusQeKjF7ghv/cL0qTaSiGtMsXRfmommkrGUBw5LO9THq8S9Jp7jbNvOj9IGZaFW+spDyVhI9Rh4WwP5mEFkjqwQz0CTkYotj4ZBO5mBHqJhqJv7EFDGMZj0PYFdcovvaydUHhUcxh5oIkP6sRFXs1QJxmBZX+dB75QTLqUZTZs2fY=
    APPRISE_URLS: AgA51cA6I8ONOytnQJenrNxfRsBLJ+xdh18pMsWNI1N1SAOd1HOCHpktiuaKmLfNO/oKvZ63I5C83F3wYAx/NWJEba6WSHzMaoJ0HNBYWQ87XUhP/r+a7HKSjlVLnwv62xbdqYzYu+HJgiNLuo7HRf+0a6G+XvWWd8VSmaiaBAQM8l7OcFRLGc6bYsfLCi6ENVuKp1VqJtYqbFAEvTc8uBDS1vzQtv97os5B9xbMcwMdJrRhY3lGhcZIlMzp/bKX5wYlZ8QKXehb83VgTJqEMq5Cj2usj2oo1P+IZTWo15PYNGOFNK5LeLIOSzAQIQpnVku/fqCOS3P0lfwbggnE3kSxpwpyROMpwQUggjYIAYfijj73ukE8uQkve/au+HhF12KrBm/4fvskaFGwLNWUDIWAcpVMTuNoZQ+9s0M9VPvICjceoSl0J7sPFksgAt4CrDqojV9NmYtiMXxjbPs+NPGuB5X6M9UzjoeLpevupa8mx+3YjDVlBpUvO2RPKp78vTTbIi9Rpm0gK6XtYMVXWnv3/ffs5PmdetBk2i8RSvrZpdOiSRtml4lip5N3E2zvrkm/BaoAAvyq9tXI5tdJp62oJhcWhnjpW8OtVaSHQHWjyCEa2YWHJKYKb57g6snAqUMmItYfLKBlN6AdfhgxAW4rZu8EkcBqPo6+FsaU3lWGhVVCpefs+fQUcSfveVxLpq/mEfOLHq9b0zKUOj3YgvCHEe1m/eNVgyYMnJPA4E0SJP16jlgRA8utYkfcZzWbRg1sz+bnDTXUOhJJu0JbyW0PBQ==
  template:
    metadata:
      name: apprise-secrets
      namespace: apprise
    type: Opaque
