---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-secrets
  namespace: apprise
spec:
  encryptedData:
    APPRISE_STATEFUL_MODE: AgAZLb0D5b8URYtslvR3dsdqe0HboM4rN6yAQ4OvRM+ky4ZalrAp0OJSS4/HF25Edg4ozWotFjNAf1pvXzjMcMGJleSmxM/nBSblQZYy/vuFsP06C+3efHzMLJcTaO//TJhgKSgnPSJ2GEppGMuNXMt+wwmb24hIo775otUHIdSMOoA3beiFzPs2FWzBukCn2mDwTKoVQQFBlrrZBT67TwHHX+en9IxlhhzVErYbbhins/LWmLu2euiGrUb4FDWLQRAME+aiP9vAt1zcTyBH1lTCVQcQnXzDG1OWrPa6RqEs7ITYhatET+NhXCySeoyDFbppHezpewiLsB0ipqToDS75/ssJTFxFfujvi+h3s5w1GNXgCTOosHPEUgx+iFqdn/KD6C4rgr2U5Fz5PFjhx2b2KKar5sI9z+ivPsrXGrYeNBbk1ccIIn3Mr0pVBEalmnS3uz4fsfRVJtrBTZ75GXd0apLwIlUTgXPcjnInczTONv/f4aMOIfnrEyCJcAUORXxC1+TlGvhycTa9mxOWgBru/GlMiycI+gC2tK6LVj55o29XZLoRSalhgC29r1NHE5atUr1Gqx1UhphPQg/YcYiN276Egx8tucrBaGezRhjv+GFiXOsHwLqKbA46zmijyy8Y4WsZgG65LokiuZGT7caCz9s1rcdcm6dVnhGj+fKpTMhKNggLeJNKZR+9MmRDg0DMZ+WUzc0=
    APPRISE_URLS: AgC7QOtxDjuf2QfJud+wnutKqGm0IAj2jvNcxHqc5sUV16nW6iIt248e7BCuGyKs3+1Upy9yrlvrEBS7Hf78SGBtIn0E4RSWO5leoFIVKKy/I4t1YIfStzGtffCoZ6MUvBErHDJ7jseFcg9svBnsxJ2/Xg4CYTndNl/W1iFHSYyWgzsB8BuzVq40oVOTjO+8Vtf67N9csuFzFuJa/ZS0f7BX2V4qUk0+W3f87iDZXQkXawEiXOfFjQb33ZXBra+H4+n6lwBKu6kvTkvRHhc6XxDWMoxxf4V6Ng3V9F4NwO+6xb0BL1FqWfjh9CeQyfU0TR59sSUGi0HtCS5ZfBWuNHHxG+7fYVX3r7iu0Ej098ZdnV19k9DP+w+hy6Vil0STK9V2TO6aFuhpYKjbVvckMXbVVg3o8SxgcIy+WtBt9dW+Q0dqr2mKs4wL7a95B98FbsQfZ5B0hZbzvcmThJD+LRtsgN/idIUTyPntTY0evEIyRvXQgQo24yAPWxB3gelvCvngSwvfSXWm9lqnzsCRw2VZbUefCWeCLkR3+5rY7Gl8FWRcvkhBzgXlLAEIK2jV6d5t/xvnUThfEKnCQMsrNrPRYm7tROM0XzRk+nyQsQ47RhP53zyh3wstUUzl5xEc8SM/gMFN7ARLkXVzj5fjztJv3+UeByvxis1Ie6KL9xLyOgT6jegGHFEkxaZ1cTfdGx5nsNRYM7CaybscjlCa/p3nktXucwqF2tkx2YT0ZwABDG304UWogPVfRnmhfxxFYb9M+wmrY0X1vgw+64hQiANgTw==
  template:
    metadata:
      name: apprise-secrets
      namespace: apprise
    type: Opaque
