
services:
  vaultwarden:
    image: vaultwarden/server:1.34.1-alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: ${DOMAIN}
      SIGNUPS_ALLOWED: "false"
    volumes:
      - /volume2/docker/vaultwarden/volumes/data:/data:rw
    ports:
      - 10001:80
      