services:
  actual_server:
    image: docker.io/actualbudget/actual-server:nightly
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # See all options and more details at https://actualbudget.org/docs/config/
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      - /volume2/docker/actualbudget/volumes/data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actualbudget.rule=Host(`budget.nmoura.pt`)"
      - "traefik.http.routers.actualbudget.entrypoints=web"
      - "traefik.http.services.actualbudget.loadbalancer.server.port=5006"
    networks:
      - prod_net

networks:
  prod_net:
    external: true