cluster:
  extraManifests:
    - https://git.nmoura.pt/nuno/homelab/raw/branch/main/kubernetes/omni/templates/manifests/cilium_manifests.yaml?token=${ARGO_REPO_TOKEN}
    - https://git.nmoura.pt/nuno/homelab/raw/branch/main/kubernetes/omni/templates/manifests/l2_announcements.yaml?token=${ARGO_REPO_TOKEN}
    - https://git.nmoura.pt/nuno/homelab/raw/branch/main/kubernetes/omni/templates/manifests/ip_pool.yaml?token=${ARGO_REPO_TOKEN}