apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profilarr-config
  namespace: profilarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
