apiVersion: v1
kind: Service
metadata:
  name: profilarr
  namespace: profilarr
  labels:
    app: profilarr
spec:
  type: ClusterIP
  ports:
    - port: 6868
      targetPort: 6868
      protocol: TCP
      name: http
  selector:
    app: profilarr
