apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
  labels:
    app: forgejo-runner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      labels:
        app: forgejo-runner
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: dind
          image: docker:28-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          command:
            - dockerd
            - --host=tcp://0.0.0.0:2375
            - --tls=false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
        - name: runner
          image: code.forgejo.org/forgejo/runner:12.11.1
          workingDir: /data
          command:
            - forgejo-runner
            - daemon
            - --config
            - /config.yaml
            - --url
            - http://forgejo.forgejo.svc.cluster.local:3000
            - --uuid
            - 13b436f5-4f38-4bbf-a3bd-2508bd444092
            - --token-url
            - file:///secrets/token
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
            - name: token
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-runner-data
        - name: dind-storage
          emptyDir: {}
        - name: config
          configMap:
            name: forgejo-runner-config
        - name: token
          secret:
            secretName: forgejo-runner-secrets
            items:
              - key: token
                path: token
