---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secrets
  namespace: forgejo-runner
spec:
  encryptedData:
    FORGEJO_RUNNER_REGISTRATION_TOKEN: AgBAiuUOa72q/e9AfjEfVwKMcjHVKqZ15yYqShr9pxwOk3Z7o/BgMsEC9QG1On/WNOW2PlkGbIBNNuC1wH1o3Bqp4LkKo2a5WoYFf1yOU196nEkQ8uSucXIGDE2ROxr5KINe4Fn9wWGP6BzBPW9dC6TtI7W2t6u4jVTA4UpZNLSk/RyPvFj5/Gg8LMNoWsUZnc89Rm3sQS8VVAOnOnyopIY0Bvlwnzx0tmvJOe145x87oysv0bfcRfZ1QgjEO5YqyDuUc1clJifQ3XxIiUl/wN99BgY5Z5eUVaxG544/KkpWUTCcMRvzB5xzb3wam8ddicK79el6nsalUgkvCHK4Bo2O+CWC/NNm4lX8R2WYes6nTL+bGqUdxIsEZBKXJuxhwtbOPHf/nne+xh4sL1MN7x2DBgCo+nEVOWv8tdg9BnaoIMD5CPU/Ja0DfwceotqYPs3cj6kNYjHxxAxoKyvaCyq43OlOeud7cjp+E8GuKB0rcMO/r7xY0hUc6M/VbjkDAfnzGtsueuVL9g/QlE0ZSJ/TsTRoQmhJNNRBZ3xF2VygqfKSscUJVbmcrfx9P82cO4WEMcPLrp7aTSEca7+QvForoapuXeEpIawkWRj2t2mmXASGQhIWkcU7Vos9+VxxdWSMt1/uJON43DtYMol1hYnbi5AYNJ232nlnzFa+ENT8AKexADSVl8MIca7f+uDQxDfqjQlTqkhQauaFFhOMfexW0ofHglejSjhxw/V/yB7CWZImE3cQ2rxX
  template:
    metadata:
      name: forgejo-runner-secrets
      namespace: forgejo-runner
    type: Opaque
