---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secrets
  namespace: forgejo-runner
spec:
  encryptedData:
    token: AgBo5NrY3U3/kmjIQPiBqijaKnOCPT1RQIt1q38Xmr2hVqLCT3VtIBnLSSpDi/8EdMUujb9IFKUocqvTPPcRrTBXEpAqSeVULV/L48qRpIeWOSMZSOI1cmy9CoOmoiT+9b5KYxIdFxvt6zyQvBcXAypo6ckj84Jtev6TD3p0GbVwyzw/ucQ3n0FOay696t3v4JeRlSLtzuYD8olygM0dUFDxd8o2kAkmGrtqz+kG8DqDKCkb/uk9pFMlyqtzBpzPFnqoMjrqZPBeLWUhqzmcXTZpZI10rPMrtsRzhVMJW+508xWSW9GrTWinGUIoym6bG+QhCzhcFbKr9CmcazjGPrDYEstddGUle1GeUMQo59Q3zXr2x5J1Mpq8M1pjJHokm950aqIu5YQ0uVuihIACPV+6uISN7Uzmpo29ZnAPHrQdP2ac3OsWk0cF1wpNQCga4rllC6lYvkm1q1wSL7ko3W9ySkPCYMwSIavpGlUHXeRb2aTOLJsPwr+UMv3ESIeNwNcrZ+m84sVnBG7N4mvItv+n2NTywiaaDIisQlxCIKC5bYUvHZIEsALQrNlXAMOwKn124iLw6Ph3dKVYIx42Dxz8yS+DDDWXqd7SJm6dx8vDMilOn5oUNlaHF+ewxbz+wlTPyubepkffUPhujphUSTrcDZKxAlnPgObagZumIzK1KvK5KlcXETHMf3G5FTC+NyjL/w+WbPiPSTN9Rtp5TFi3O74dRICTAzxtxAMwaoUeFgbafRwHVVi1
  template:
    metadata:
      name: forgejo-runner-secrets
      namespace: forgejo-runner
    type: Opaque
