---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-secrets
  namespace: bazarr
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBlFTPZi5OknFdYF+Fom7pIcxKeFwx7lpesM1beWfVI6L9yyXDcuE/RLc8nDLnUoB0uAtW8gfxnvIowlh5TRmb5hY4A34A10+A97YVHBDm58J8aOk6QPvejyFDkG0N6/75HPWLi41rntBE3yo8U82vk/d0e7olguFw6FzO8rhCbDy+l1ieD7/uHsSYWJRL1dxCDs9FKehWfZtGlmVuHocR6FscKJc9gLWhfVry4gD2jAYYDJk4MVTiDKXWqe/rXYqKE8ldu9VoRs3SdnsPN2ZtBzp+tnR2VvAjzIJLz9ixpkrLo57rMFBP/OgMgmGRRDNIDghKUiyvmcVlKQGaIYmQ6KWHrjt43QybeMZWMIVZbYzomSVGzEf99cyqCXJNATCUTEIoelryIrC4Vni0NBVcZxnMHBMBg0bfuTE+0Vbdx9ZLLaLEFzonIxo6cicaq5F08dHRw4Cja6ZLpKMOMgaEMsSjkZVxXV5SmDGU2Y2o7TN7TFekhtGw+PAl6SvTw7aYdZffm/D7LYSS0rQelGwRigvRC7k1ma3AZ9s7yt/OWnabubiEmyjypIeZW9PLRngkzK6iHpSmQYG+1enJEDh10//GFweDf927ZchkyygW/Lh2zccDIrlC2v5qAJ+Bz2MzWnRsMPiU0fHu2xx1neO+rBUuCndNKEn0e7iEdG+IfkKJbvbNUM7K+R9CN1srNADkn1vHLoDkhvF3M/sbAeedoS46FnjucJHxTKBdniYkrXw==
    POSTGRES_USERNAME: AgAhUgLQgZWopgGre9svPc2pwfWqcPbWP6Kzb8HtviY09/tFtY7jZcBXcITHcF0pNBEEf/WelrNlBtWWOq9/HM+51D6b4iiTKjbCV7qf5QdBQi+eRzEHbFYzidZhmRI4/PrJGoNfYv4Tams1dD1bJsTTdtUTCsAoe1jlvlNhaArooi0QQt5tKTuIRrYHB0k8TG6NA1CAGDXjmSMwAgLoh6RCeDQ4eaumMkZgrSIJqLptWvWMsiNztOSaBgFVb6OW/bcolgV9HzNFaKahFNrXtJCh1YxjpvrlmXJkIdCjle3qxXaiQxTQsKTbZoBuoaKotmSYIN6KrQycfnyAhc6916nyKxA8zn4TiKO+yqHUg9DgI9c32SbwrK2oiYMT31BGkMtfP9u41IIbDZ6/1dBiihk6WLjLmP1ylcaYGn7tx7OSwaj7OqCwBZdYAGHpOxlI5vhgYzQFUg+DGPhkbXzfek8GGKzCn7370ZAkgS6t8rANtQHEI7Ng95zY56VcgOzFC+XEWwfkmjqkkVm938o9DXGzxtGNcV4SeofTdHwpq3FrIPWiMYpvGA2pDjGQRoqI1LZxtcfs9OIpHQkz7mIVD6fsWpTlPS+X1mn/ZPJxPkz5bsbiAdjUTDjH4DqeHudwHq1LaTo/3CqJUJvlfGJfuoITkKeLgHfgTXLJamlXR1gdkqsgBA2UmPIVL+/TidvlPTEs2Tpu7+QiFtGxlw==
  template:
    metadata:
      name: bazarr-secrets
      namespace: bazarr
    type: Opaque
