---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-secrets
  namespace: bazarr
spec:
  encryptedData:
    BAZARR_POSTGRESQL__PASSWORD: AgCaX5LIo2mKwq3Qo3kra5FBT6Z4rthRiSLMWCT30sJED7IywvKrcA9s3OVePqUPFKtGrqo9TwoprbyKKr7UED8GY56BTkRE+5N+jGs5vXVA9Adtoxzt90fQ5xKV0+cCQbQ1QSoS0BTK8fn3GR0V7nh8jPqi8Gr3b+IwKgl26s5sNhJN341N3U9sHi0zWPkG8ntDRgw38mreE3aDrAlb9rljQrrgp+uwWLeAizuxFJIY5mDc9+alp2ictXUSj/zHHQzRxG4mRnHv43StXpmgk5B3sGfLIVa7RStpiigUDv6jmkEL9qLOWnn8SZZkJe8hcjIoCuYgSm8bVMJ5aV1qIoa/ZD7seZKMP04z/g3iQw8tA/RadWkdnKLU3rL4xYVgwi6W0H2LUnAzProGzAtNNc5M4pNQjJSSDXtujrh9hoiMTUhd/pduR7LsGPHhc4x70VgIYYOAlOUQwXNFXm51vb+pF29vh4zOlR0NbNDqxCJdOLTVt57Kn1owXF2x7t79sju1fH4ZYOR95Ivw2BzMAXLBmFh/WxVEkDeWRXY7b470ZTFF78U20yRliMjMGRXdQhLGwNznJ2PX1EJifxWiXtBHZu3Py19c0v0//1kswOq/AJEOD9pNp2BOiM8Nv5n6gijLBAUpCb8X9Syzmi/pGquV5I8KZ4XtNMf6CBIzfg7mSfOUks5Es/CtQEpaj1b54TEQK8mbp+eGQyAxRYx+6zB1UtxXA0e7wUDDSskw7JrxTQ==
    BAZARR_POSTGRESQL__USERNAME: AgBwW1XzAhxBncA7OKXKzxKJFcoDF3pg58FdTJA0lCJ8eViyidulSCGB9URUk5tBSPIsM1xZhhyc1dQJigtnXrKwLAU0krKAm9rlF1LikNcsjmb3Pi7SwQp88ZyvoJG5H9b2o1X6MPBXYKfTcKAyuUTdwiuyWo3GOgmPN/HOjNZHCRRPXOfCQdVZwo4ew0miJY/lXurtSPtUjCO+2F6UAR7dOjK93LjWcljBpkrTaRyO8p4t7gH6SRX/A4UY3e0qK9cwkrlejljP4BuZycGv1TMYEE6jzH5hLHOL5rw1Ojp9/RRhdb53ssbzZ4G7AuuikZKK0kYSrH+JiwT1oRlr6FSjMvSyv3E0ikLrTiHO6Ju1hkTR+LtyiSELM4URnKha5D8aReEgv7yZjLC5xluqe6n4Qm/5qw4Lhm63a2DD7y6NcleDsA23KegimwcedfnMlPLaK/0eIJvUbJAxF/TG4YjpDPWyNlLxZ7xjPiA6J2/2yRkKoRwy06ZjKAn4eF7dvW4/k58rVJ9tCEBWGHOIJ/5oiDjmYTRzVq9QAqOtREWN77ARIRBWVSfDnPaFU30oxmcwtA7TaHGUthwXP3AujyLXbePTTT7J2keG1F9SPE68X/PE8TKf0sUEDug8SGY4VBmcjIeVpGxCbH9tqtfppL2TL3YqqCTWjhqsaHj9Otw3yncGFrcQPyD65zAoE0KPlNSpbjdgfBvsxPShpg==
  template:
    metadata:
      name: bazarr-secrets
      namespace: bazarr
    type: Opaque
