---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-secrets
  namespace: bazarr
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAMs0sNlXu0iT1RHxp0DkABUIQfq6yWfVafhPME851ymR+yfOYZPvZ3HUpUgN9OYo+T02LJBWpWa4ssDLLy1dbDTWwqhNlfxv2W1Up2ORcekyI648cj4msTEhuBkNplRZiCI3kydIIFbrXlFrdzG7xiImZsOyQJqW0prpNeAX96BtTqc9HDnnFEcA2PlX1EGR8Jt5ptJN9ZKQgeNGFSEVxTlynz1kU5VDBlN/s1YsJJ4owifscEUqkHb20zT4uVqhka0LUwYJ+cDx56iOTo68o2sMjUD/S81p/92M6oNdH5IojVdHseofzEsqF9fAvJihmHQxcEpgCX+9sQQOQAG1tDSL7WkVwBjrI4DHW3KUPHQsXL4e1TnMoGyBc+ccNRZ7i4FNtuyAWR4kIiyjd34rcR6RevPgzEyDmPP1u43dIwxNBWInM4Iw4SsFZaKoDyQUl300ZuQgHhXXTjKwmSEdEfUgjbxjncfM2qlNVN5yIHEEyPHeRw1XuHKS41bnWFZdWiN/drBFexK5HUTRI2C8/d26f7RxcWgYX8BpogMa3kBvsmRIDiYzgu8rm4ox6o2a7ZeOWf57rjmDa0ThP0UZXWYgdhGOn4ih2sMels97qSEkx9axoxls1IuhXKEl7R1EI3BqE/h5iBCMTx//Sit/bF/q9Pf53CaIwcfsbMXMEaMVHVB4TPTYF6HubWwCVjPsagjV1F39r9Xmqhgc7zzMumccCqxDkCqmU7xJn2ydpC+g==
    POSTGRES_USERNAME: AgAl3wyid7ArbvzzQK9+0fSL8au7sB3wwZSUkZz5Z6d9N+BXoZ3x17wuY1+3aS6n+kboxsafVY3FWZISDXPztm7eI1xSKyKq5cLHK3Tx607jj6pHeH8F4gS4rJKvwRcBYEW7UVGtNLlgvbSkTy4y/DXOvdr36wVXP4hHivhn61tolxavH0dsl6MUC9tBWFIVuKlgEqGjV6K9teUtXcCUThUPAGxDAnfHiWVKL9PoTWiw7wbB5bf8KqyX40iHsaV4DSXJxKOBKFVl3HwXmHo0/DzWnI0kse4kia5XsrqdQcu9+RmKLnUqBYMbC4tQ2YhMvahUPdRoMyeaM2ooodAGx08bDkpOmyMYeaVaY3jEjMpp4zcX8kcrVUrO8IrT7KUzxeTM/+uCcrfopZ5KG3pFZoA+l5Rb+cWgKbTbhdzdItaQriGc8xWX9VlMnipbpVo26XVjrj9tkuKgcgYuC+vMIt1bxAj5Vlyf1bqKFOrLnSyvdvgBgGzju/lol5fU0uEljjl16nby2NEgzfpoK8CmD7+UQeP5c+zW/KrxY3aUh/agtp/lB0IL3tJkAjhhh8gMK8PTqciOSyLyB0IKlvb+kFddx/e1iwpgoLla+85LK4Qj4DReECWeWCD5JLNVrzZNB8KFnmaHf+Q1bTBnBTniL5CKSh9WOG6KpquVVGqgTCy6UXTaSZyv0JK8HyRL3M1DNlE7ylV7qUz7mSBZ0A==
  template:
    metadata:
      name: bazarr-secrets
      namespace: bazarr
    type: Opaque
