apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-media
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data/paperless/media"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: paperless
    name: pvc-paperless-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-paperless-media
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-paperless-media
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-consume
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data/paperless/consume"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: paperless
    name: pvc-paperless-consume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-paperless-consume
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-paperless-consume
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-export
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data/paperless/export"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: paperless
    name: pvc-paperless-export
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-paperless-export
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-paperless-export
  storageClassName: ""
