apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  namespace: autobrr
  labels:
    app: autobrr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: autobrr
  template:
    metadata:
      labels:
        app: autobrr
    spec:
      containers:
        - name: autobrr
          image: ghcr.io/nmourapt/autobrr-qbitrace:v1.73.0
          ports:
            - containerPort: 7474
              protocol: TCP
              name: http
          env:
            - name: AUTOBRR__DATABASE_TYPE
              value: postgres
            - name: AUTOBRR__POSTGRES_HOST
              value: "192.168.202.1"
            - name: AUTOBRR__POSTGRES_PORT
              value: "10011"
            - name: AUTOBRR__POSTGRES_DATABASE
              value: autobrr
            - name: AUTOBRR__POSTGRES_SSLMODE
              value: disable
            - name: AUTOBRR__OIDC_ENABLED
              value: "true"
            - name: AUTOBRR__OIDC_REDIRECT_URL
              value: "https://autobrr.<path:cert-manager:domain-config#domain>/api/auth/oidc/callback"
            - name: AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN
              value: "false"
          envFrom:
            - secretRef:
                name: autobrr-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: autobrr-config
