
services:
  cloudflared_lis_isp:
    image: cloudflare/cloudflared:2025.10.0
    container_name: cloudflared_lis_isp
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      vlan1:
        ipv4_address: "192.168.1.65"

networks:
  vlan1:
    external: true
