
services:
  cloudflared_lis_isp:
    image: cloudflare/cloudflared:2025.6.0
    container_name: cloudflared_lis_isp
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      vlan1:
          ipv4_address: "192.168.1.65"
networks:
  vlan1:
    driver: macvlan
    driver_opts:
      parent: eth0.1
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.64/27
          gateway: 192.168.1.254
