---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: booklore-secrets
  namespace: booklore
spec:
  encryptedData:
    DB_PASSWORD: AgChsjL5BFg5XtA7acqxd3eFQSjqLw913L6gOZ6+MTLhMZbVJcG94iTYlMBteqjewymhFbQUsKIxx3yCxg7BxO4OH+qDuglYfKvZc/orz5wi9hZYxRr5pdDBU8+bl5jaQtORHBLgxccxmBbauKk5AkfYgyRv+pGN6emhEi+YxDdpHkfHIcfzK8aaG/AEd/E47aCWiRdGTdieP6YK9Sndhq/leqvm+3FKjqmAsRNXPGniNt1kR255lxfEvaPm4g6DU7ZDDjMjpRK8x34e8S2lawUxofL0VuSPpNo8pajY21RQ1spUOaQToBBLHdi2KDMDlNgYaNxUNqFy/9o4HifBF/oK0xsZ/Knhe6SwD6PEc+dLzmeIycXj4yjWIb+6b5mTAMLAZ7risq2PR2djQ85yekual9oTnr8q35Va+3Nf0Los1supKfFSZQMIHl8o0NALd2Usvc+dHXOw4cUvkQyspfhSQOVNt8hVNFLkSP9UAG/uJU8rMBJhlVQfXDsjhxaVwk928NErfN3wdpRAsypdFhPXNMcQX2z9jGBK6j9/zUr8wqIXC40IdkldTVioIrwKJCCLaODL5JoKRPCRIfYojy4TegvEvmjFc7BrLyXASY5DNHdBv9Cuqh3XafPdPn0JqdlLpb/UyW4gBq8NBSNtYkHHuOuTPl0LzITRnb87wcZWpbDTWHMx8tGfnrw1wVyKQtxmsW7bSjtXuWnGWdu8u385vao=
    MYSQL_ROOT_PASSWORD: AgCF0k1rQFmsXh+DRnlLvxU2BxR1ipg6MhA9JqHVvXsVMykQX72UnktN1USrcOQ6O2IzpO+ViJe1vzdp4wacO4frO7nzQi3GRmIngVPZHJ+/qUaRic7g+WyND2o5D1d7iSuOrx9NJrX6t7LNbkbxFUL/IN4Ih3taLTtAOEz9Z/gEQC2MfKWdkr5IljoqWDm9WzaIKX8IFch7HuRoX6mDmzHD30iHsgQoSJ25G3DjgvUFpZjc38t0X2O7vOOBDjGbgNc/Nl1NXjKyK60SAeRfXrjfzRO0IzspJnVgJ7LASfSDQV75SmKbLW8MzurDTJWPH0srCC/u8RtLixpepHs+6O7VXj3QJcGXOUPWfJICEXnswkHRb6Q4I9HLUaV6X9LGp8hWwhgDlD1WDbLafkXBqgnBSSCIr4OhJWl5ElCnoDr10fXvurAx1rq3EleoYI/o+uCoNN5NNmndbEhU8vLiYJBJ2h66KKKquO0CFdSuGhQPpNzk486F7wdA576FRsDobVycxwpN5NMnCbhMf8CUGZ66eoLvKSl40uiSISxOxeL23YTFWEe0YS4LXO59kvohY2MVRT3aV5dGuks7PPvXLTxpRzBap00vYEFuaJk4KJN6YmhgoJQSt2OYr/9MmI9JcJ53oVl7Q3NF5bh0IUIyO6baOfnkBl24K7IAGtqQmtS9DZIMXMfbXq7MrBSy+hvbVsa00xO7U2C4hjRg8hq8how1j+IrMkTOqA==
  template:
    metadata:
      name: booklore-secrets
      namespace: booklore
    type: Opaque
