---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: booklore-secrets
  namespace: booklore
spec:
  encryptedData:
    DB_PASSWORD: AgCdLYvW+NykyLaAkprsxUEnM8FnzDv0mcjNa+3cKR79vqBX7J2i5T2lAb0/heOOF/PH+GiwAaN66yuBvY4CG5knNGgnaZ3n7rL/KUfm5tNeyNdlUqmm16LCOqqawLTR6I8fjzwkTfV/1Jzmlwq24idqY2dWE8ddV+1HUYwh5YpQaYtoy8dtvkmSbnBBUxPMMNu36raSTrSlHZg4CseEiegJJr/fvgShwKn3RC5erVFnNg+B8Ag3rOeej8RKz3a7Fgm2yPcERHI9dskYWRQmXJs7rw0oVMD1+VBehiDd80AGSQNrrxo5ZL3UeTAwwZnHECLm7UydX6h3pUZHlIltTO+8TKAjouil/ZH2vUq3Ga3uO+/VcKlVk542cjAMlQXoU2HhTEddwsA0bGAnM11/XFah7wAJ7EjDerFa1BIfX7ttvTpO903Nv6IC4koKtRZ6p8aLpZr7AWWGP23PetNeCcMfrxbmVXlmXGj5vDuH7d0qMIBmq/d/71FAsZIa/pk1K37NI6ul3iVaQNvHYy13MfsOX2h6hRXgelLiCgn2hTHU5xx9trOiYjIO/nl/Rx0qeRPpLu8ikjJfWpM/WL9RX3vb6zVWGhgN/6AcVerUmKtuzJZ3NqgfarEa/VSFd2pj5fH3/fEC7t/SBfFbK9TxLWMXemF2oC6UVV8fCoz/8sSjxWK55CbORGEKSj3vrzft7kFNFrMVhTo/XKYt/CuYchXyPyc=
  template:
    metadata:
      name: booklore-secrets
      namespace: booklore
    type: Opaque
