---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: booklore-secrets
  namespace: booklore
spec:
  encryptedData:
    DB_PASSWORD: AgBCjzEe1AoCjyymK+dmnVgczFOADJ9MGnBAsGV8uZjEvEqzHJPfJKKvsOwE103l872ocpA13NPBrWdNB8lekFCP9hryD6KKMafrA6GuxL9WNDmQm+D9+++zztKlosbm2RF6NW4SizUoA9Ikhx/f9C58ybY53D6fqPAmGadF8PlXENzJ/YVi+5sg59E/137+r377NOL9Fs/1xm/ySQnsQ/D4y22sjIgh8AOP03i+NbmjQ3O1iEEk/SJyT7GLS0yadps0mWkdugr/U2V7LBBGrsUQa5uOn2Hnj8mDvXw7fbHxkqvePaluWdaGP42entiViE+xjzolvV6O2Rd6UCYwnu1NNgE7yzY2LQOKvHyO5TQLNCAacjBxzcEzN8MITVP01ac0hsYw/Vbv5cD41jNK+U3w8oZglc4QOnHx6fToTniRSggg8/gzQ9smOwV2ZMuf6yfj2ZGKOWMJAttdQVTcUjDxXi6t8hDcmoMV1wKmQBv/fTSeZdIUG4Zx/tm1SprWY+prz4ogMstHR1hbxNxFzWTc8UumG0Rrb52QL6w9MsIhV2gE4dPDtnHPNFZxcR4/sZHzGoVqtbKILIJwqYcgehqoxnxESX/bmTTDB/rKGqnCJ0nxFLMsE2G+1vLDG4L3I4iFOdB8P7SuVGwtkv4QVl/2/3PnQHOW+stOeOKO0TcZBjPwK6r/sAf4f/tuUWleuUzNl78tRrZE4FFQQhNzkNyPKqobIVDLOreHSrCS2SoJGA==
  template:
    metadata:
      name: booklore-secrets
      namespace: booklore
    type: Opaque
