apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklore
  namespace: booklore
  labels:
    app: booklore
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: booklore
  template:
    metadata:
      labels:
        app: booklore
    spec:
      containers:
        - name: booklore
          image: booklore/booklore:latest
          ports:
            - containerPort: 6060
              protocol: TCP
              name: http
          env:
            - name: USER_ID
              value: "1026"
            - name: GROUP_ID
              value: "100"
            - name: TZ
              value: "Europe/Lisbon"
            - name: DATABASE_URL
              value: "jdbc:mariadb://localhost:3306/booklore"
            - name: DATABASE_USERNAME
              value: "booklore"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore-secrets
                  key: DB_PASSWORD
            - name: DISK_TYPE
              value: "NETWORK"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /books
              name: books
            - mountPath: /bookdrop
              name: bookdrop
        - name: mariadb
          image: lscr.io/linuxserver/mariadb:11.4.5
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
            - name: TZ
              value: "Europe/Lisbon"
            - name: MYSQL_DATABASE
              value: "booklore"
            - name: MYSQL_USER
              value: "booklore"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore-secrets
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore-secrets
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /config
              name: mariadb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: booklore-data
        - name: mariadb
          persistentVolumeClaim:
            claimName: booklore-mariadb
        - name: books
          persistentVolumeClaim:
            claimName: pvc-booklore-synology
        - name: bookdrop
          persistentVolumeClaim:
            claimName: pvc-booklore-synology
