apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklore
  namespace: booklore
  labels:
    app: booklore
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: booklore
  template:
    metadata:
      labels:
        app: booklore
    spec:
      containers:
        - name: booklore
          image: booklore/booklore:latest
          ports:
            - containerPort: 6060
              protocol: TCP
              name: http
          env:
            - name: USER_ID
              value: "1026"
            - name: GROUP_ID
              value: "100"
            - name: TZ
              value: "Europe/Lisbon"
            - name: DATABASE_URL
              value: "jdbc:mariadb://192.168.202.1:10012/booklore"
            - name: DATABASE_USERNAME
              value: "rotunda9344"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booklore-secrets
                  key: DB_PASSWORD
            - name: DISK_TYPE
              value: "NETWORK"
            - name: BOOKLORE_PORT
              value: "6060"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1536Mi
          volumeMounts:
            - mountPath: /app/data
              name: data
            - mountPath: /books
              name: books
            - mountPath: /bookdrop
              name: bookdrop
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: booklore-data
        - name: books
          persistentVolumeClaim:
            claimName: pvc-booklore-library
        - name: bookdrop
          persistentVolumeClaim:
            claimName: pvc-booklore-bookdrop
