apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-booklore-bookdrop
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data/media/books"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: booklore
    name: pvc-booklore-bookdrop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-booklore-bookdrop
  namespace: booklore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-booklore-bookdrop
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-booklore-library
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data/media/bookdrop_library"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: booklore
    name: pvc-booklore-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-booklore-library
  namespace: booklore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-booklore-library
  storageClassName: ""
