apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-data
  namespace: booklore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 5Gi
