apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lidarr-synology
spec:
  capacity:
    storage: 1Ki
  accessModes:
    - ReadWriteMany
  nfs:
    server: "192.168.202.1"
    path: "/volume1/data"
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: lidarr
    name: pvc-lidarr-synology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lidarr-synology
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-lidarr-synology
  storageClassName: ""
