apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: lidarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 5Gi
