---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aurral-secrets
  namespace: aurral
spec:
  encryptedData:
    SOULSEEK_PASSWORD: AgAsivpfWN+mBGGMvkvUoZmagbs5ZZtelDmHP/QH25Dj1Hp1xLdkLSrUndcl5dcDatjhLVfKilFDcVCQrLIGiJgz+rM0ODsqE9tZRxqcUfGItN9zOch9DvtPrE4b6KRE71chMYxLj/ginudTFg/jlB0HItQSKJMitvfxQRLh8iIGGHDLi0pyw+iTmm/ojZEQipHGFA3OeB7JTy8Qn4Wi4etRYLhobLT9sEmSCo2Puyf5fjMNWmVmiVyFqXSSoe3pSCJatocU29asRnE7wSkpCoviDxvsnyPWrdRL875neHU5+PblPWR8GbXPZkLCj2zjRCmnZCXw1CfqFWKBHi29Oc1wn2hO5w+o3kH5DqHU/xKPBBHWsHeqO2DgVx3DvU14kr3cTJMG2c9Z6O7rP0WJ78hJioJckzjbw3WcoqtUwCw76LVxypR536y2IPVIKSqRcfxrfjq1mNUoT0zawmJfm7r1zTHXmjMlL39BiwC5o75lLNy0P0zn6eu2q9BDNXNUuY7XHdsOVybt+PxdfDIei2NLXL3rqgYQf4dcNfgZaLZ8ew2ZHKEGiK/MpRJkL3IW2fu1ffFuesIfHdwk88DilBdI0k3Y1uxIkFoXuahqzwAhKFb7Xv058evSQOCEwFXbro8P+prnidBKe2DEdSxhwuO86j3P4VLr8+VqSM+ihWxwuW2AwI3JpdrOff+kTTJsc9/1MwkfPLdKb5Cj2dPduAE6WuLvw8MYyGbOE6Vb9tyePw==
    SOULSEEK_USERNAME: AgCssWWNVUygyxO5YUrekym4+Omx6Y5Z3OqkzjPVP+OIso71hGS23bjMGjxsc5qcGBbMXUju8ke4+D5mQyTMedtentRrb00idFDlghSuD7sFbM2jYIpqP+PNMfRMNPn8iPpDE60PZ5NVeiIDego1tkH4j8qP4IUpe5LISPdYothhMafzv4ZKVvUSFMjfpTNkfr0SNswUppntY/8RoJ8xdLKypszv44+PMUncPlvtLCsv0R/Bnf5BefXHx8xyioQwz6oKwMyis712cfotxR+jytW5lD1wjtGiM8vnutuFrO8AXsa6RAn1XQ0OsLOeoRK22bl5bbcuY+7avAfeTIEHtRcwIZwdbWSDvjKg0VPMVMc6gVgbE+XYptMT5RdH3ph6tiF4PWs4b/vWXIATdSPTNp6EMbp0u5J8ZyhFrbYQxaCp68sfMRkSxuiqEXsCuFS6dBbN4v07ivvBuS9tSCrqXUxGDuQM3D0uVVg4NXC2yiAj1gb6dVTHaR21TvOoW3ZrkjGH7ANhx64K8d6mGeAaq4NaCoDEGQvbADpTqvNXSp+YZ/KC3FI1ufgEtjWqxLKQFuBi73uIqm4be6nC2RQejtTZ+4jKDPYZ4fgfDj5up8SRvZlOZxiElGgmG6vf+A8uzH0IhA3dq2iMhFQq/rdfarxT6Kv7Nt3Vbszc/9adHj3YJFyaj2txdcwQaBm+35HWoV+i3F7/ekxOOfc=
  template:
    metadata:
      name: aurral-secrets
      namespace: aurral
    type: Opaque
