apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aurral-config
  namespace: aurral
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 2Gi
