apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-config
  namespace: bookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 5Gi
