---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-mcp-secrets
  namespace: forgejo-mcp
spec:
  encryptedData:
    GITEA_ACCESS_TOKEN: AgA7pfRD/3ETCMP3D8gl/9kBs+9F/lm0PlTUt2S88xldMix/ZEfN69lW/GwYtXqxCWwUs9abXGUDmqcRtEUREUC3iZWSjkdv81bISQxFtBOpW9C+VQJHhWkuy4zAsTL5WL5nlvBGJ+Dw9VzJznVEszFmM3wrs968BLr9KiMw0kLd7r9wmWe1AO1zW+ZTb+zKsyQbLETs9veoQel4D7H1Mt/+mbZVg4O6m4v4udl4SRlxy2+o0QLt9a2EwRmMX/xBlX8jr1+bRx+cyDfQFSFbhzTvnLHfzRdGEW9rJsuqRxadJ3Kn8RfW58HEq0w7xwlTuZXlCUOe5uBbaG0nafhlZzgAbQavGGm201Uo+U4HxLf52c3YSNVjoTsZkUoWfKdUTzTxHHE4Yt+WKoAv7pw87Mf7RT2to4CV7tFnrzvp1lSv+9W9YPhgH9T7rggHBu41pyaxChB5LQuJQahiSUfQ6CWwFJZJWFwTuek4uoBpteDjp4VsoSLBa6BFfWTdBBnwAd94kodfVlTYAVo2DpjoMxXiP2GFRzUZMPG2fIiEwkitVNBKP1LnDWJYZbEvZ2jbMqBNmd5Eq5Uh3BXKNQFLGFskV21+MhrtDYowiE4VLFBd81BAM626A7Dvz8rRkebdaqnTfm9Hfa+iANAhDmNB4UWeau2uUuWX0kxal80u4f4VNNaKpmjm+A0tGrrFF6dfIcDn4uB+K61UcayBWlrV56rJhs1lyApoEUobjF4gI1HOcWewUE1UqfXX
  template:
    metadata:
      name: forgejo-mcp-secrets
      namespace: forgejo-mcp
    type: Opaque
