services:
  sonarr_pgsql:
    container_name: sonarr_pgsql
    image: postgres:17
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - /volume2/docker/sonarr_pgsql/volumes/data:/var/lib/postgresql/data
    ports:
      - "10004:5432"
    healthcheck:
      test: ["CMD-SHELL", "cat /initialised.txt && pg_isready -U ${PG_USER}"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
    entrypoint: >
      /bin/bash -c "
      docker-entrypoint.sh postgres &
      rm -f /initialised.txt || true &&
      until pg_isready -U postgres; do sleep 3; done &&
      psql -U ${PG_USER} -d postgres -c 'CREATE DATABASE "sonarr-main";' || true &&
      psql -U ${PG_USER} -d postgres -c 'CREATE DATABASE "sonarr-log";' || true &&
      echo done > /initialised.txt &&
      wait"
    networks:
      - prod_network

networks:
  prod_network:
    external: true